spring:
  application:
    name: consumer-app
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      SASL_MECHANISM: PLAIN
    consumer:
      auto-offset-reset: earliest
      group-id: dev-group
      value-deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
#      fetch-min-size: 100
#      max-poll-records: 1000



