spring:
  application:
    name: calculator-app
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security:
        protocol: PLAINTEXT
        SASL:
          mechanism: PLAIN
    producer:
      value-serializer: org.apache.kafka.common.serialization.IntegerSerializer

calculator:
  topic: calculator-topic

