spring:
  application:
    name: math-client-api
server:
  port: 8080

square-api:
  url: http://localhost:7001/square
cube-api:
  url: http://localhost:7001/cube

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      cube-circuit:
        minimum-number-of-calls: 3
        wait-duration-in-open-state:
          seconds: 5
      square-circuit:
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 15
        exponential-backoff-multiplier: 2.0