spring:
  application:
    name: math-client-api
server:
  port: 8080

square-api:
  url: http://localhost:9002
cube-api:
  url: http://localhost:9001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/