spring:
  application:
    name: math-client-api
server:
  port: 8080

square-api:
  url: http://localhost:7001/square
cube-api:
  url: http://localhost:7001/cube

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/