spring:
  application:
    name: square-api
server:
  port: 9002

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/