spring:
  application:
    name: square-api
server:
  port: 9002

welcome:
    message: Welcome to DOCKERIZED Square API

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    enabled: false