spring:
  application:
    name: spring_boot_rest_api
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
