spring:
  application:
    name: spring-boot-jpa-app
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true