spring:
  application:
    name: producer-api
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      SASL_MECHANISM: PLAIN
    producer:
      value-serializer: org.apache.kafka.common.serialization.DoubleSerializer
server:
  port: 8081

