apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-api
  labels:
    app: food-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food-api
  template:
    metadata:
      labels:
        app: food-api
    spec:
      containers:
        - name: food-api
          image: food-api:0.0.1
          ports:
            - containerPort: 8080