apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-api-deployment
  labels:
    app: food-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-api
  template:
    metadata:
      labels:
        app: food-api
    spec:
      containers:
        - name: food-api
          image: food-api:0.0.1
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: food-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: food-api-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80