spring:
  application:
    name: mongo-sb
  data:
    mongodb:
      database: training
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin

