services:
  palindrome-api:
    image: palindrome-api:0.0.1
    container_name: palindrome-api
    build:
      context: ./palindrome-api
      dockerfile: Dockerfile
    ports:
      - 8081:8080
  word-games-api:
    image: word-games-api:0.0.1
    container_name: word-games-api
    depends_on:
      - palindrome-api
    build:
      context: ./word-games-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PALINDROME_HOST=host.docker.internal
      - PALINDROME_PORT=8081