apiVersion: apps/v1
kind: Deployment
metadata:
  name: palindrome-api-deployment
  labels:
    app: palindrome-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palindrome-api
  template:
    metadata:
      labels:
        app: palindrome-api
    spec:
      containers:
        - name: palindrome-api
          image: palindrome-api:0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: palindrome-api-service
spec:
  selector:
    app: palindrome-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
