apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-games-api-deployment
  labels:
    app: word-games-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-games-api
  template:
    metadata:
      labels:
        app: word-games-api
    spec:
      containers:
        - name: word-games-api
          image: word-games-api:0.0.1
          env:
            - name: PALINDROME_HOST
              value: "host.docker.internal"
            - name: PALINDROME_PORT
              value: "30001"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: word-games-api-service
spec:
  selector:
    app: word-games-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
